### ISSUE TITLE
Invalid MIT-MAGIC-COOKIE-1 keyERROR: Expired activation key

### ISSUE THREAD

**Issue by rojas70** [deepmind/mujoco#38]
I had bought the regular mujoco license 200 1 year ago. Today, I am getting an `Invalid MIT-MAGIC-COOKIE-1 keyERROR: Expired activation key
` error whenever I tried to run a python3 scripts that runs a mujoco environment. 

- I tried to replace the mjkey inside `mujoco200/bin` to use the new and free license key. This did not work. 
- I tried to run sample/make in case this had some effect (it did not).
- I tried to reset the computer: the same result.  
- After that, I thought about doing the upgrade from mujoco200 to mujcoo210 - same result.
*Note: I do not get this error if I simply run mujoco210/bin/simulate ..model_file.. 
I would appreciate any insight into this.

- I tried uninstall mujoco_py with pip3, reinstall it, and rebuild the cython libraries to see if that has an effect. The buid finished with a `ERROR: Expired activation key` and updating my `PYTHONPATH`, `LD_LIBRARY_PATH`, `LD_PRELOAD`. 

Here, I am getting the following:
````
python3 train_binPicking.py --render True
Invalid MIT-MAGIC-COOKIE-1 key
You appear to be missing MuJoCo.  We expected to find the file here: /home/juan/.mujoco/mujoco200

This package only provides python bindings, the library must be installed separately.

Please follow the instructions on the README to install MuJoCo

    https://github.com/openai/mujoco-py#install-mujoco

Which can be downloaded from the website

    https://www.roboti.us/index.html

Traceback (most recent call last):
  File "train_binPicking.py", line 44, in <module>
    import robosuite as suite                                                           # will call all __init__ inside suite loading all relevant classes
  File "/home/juan/python/drl/toolsuites/robosuite/robosuite/robosuite/__init__.py", line 1, in <module>
    from robosuite.environments.base import make
  File "/home/juan/python/drl/toolsuites/robosuite/robosuite/robosuite/environments/__init__.py", line 1, in <module>
    from .base import REGISTERED_ENVS, MujocoEnv
  File "/home/juan/python/drl/toolsuites/robosuite/robosuite/robosuite/environments/base.py", line 2, in <module>
    from mujoco_py import MjSim, MjRenderContextOffscreen
  File "/media/juan/sdd/python/drl/code-bases/graphs/rlkit-relational/relSuite_env/lib/python3.8/site-packages/mujoco_py/__init__.py", line 3, in <module>
    from mujoco_py.builder import cymj, ignore_mujoco_warnings, functions, MujocoException
  File "/media/juan/sdd/python/drl/code-bases/graphs/rlkit-relational/relSuite_env/lib/python3.8/site-packages/mujoco_py/builder.py", line 509, in <module>
    mujoco_path, key_path = discover_mujoco()
  File "/media/juan/sdd/python/drl/code-bases/graphs/rlkit-relational/relSuite_env/lib/python3.8/site-packages/mujoco_py/utils.py", line 93, in discover_mujoco
    raise Exception(message)
Exception: 
You appear to be missing MuJoCo.  We expected to find the file here: /home/juan/.mujoco/mujoco200

This package only provides python bindings, the library must be installed separately.

Please follow the instructions on the README to install MuJoCo

    https://github.com/openai/mujoco-py#install-mujoco

Which can be downloaded from the website

    https://www.roboti.us/index.htm

````
Just to test things I renamed the `mujoco210` folder as `mujoco200` and uninstalled/reinstalled mujoco.py. This time there are compiler errors. I guess the latest `mujco_py` is not yet compatible with `mujoco_210`

````
Invalid MIT-MAGIC-COOKIE-1 keyImport error. Trying to rebuild mujoco_py.
Compiling /media/juan/sdd/python/drl/code-bases/graphs/rlkit-relational/relSuite_env/lib/python3.8/site-packages/mujoco_py/cymj.pyx because it depends on /media/juan/sdd/python/drl/code-bases/graphs/rlkit-relational/relSuite_env/lib/python3.8/site-packages/mujoco_py/pxd/mujoco.pxd.
[1/1] Cythonizing /media/juan/sdd/python/drl/code-bases/graphs/rlkit-relational/relSuite_env/lib/python3.8/site-packages/mujoco_py/cymj.pyx
running build_ext
building 'mujoco_py.cymj' extension
x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/media/juan/sdd/python/drl/code-bases/graphs/rlkit-relational/relSuite_env/lib/python3.8/site-packages/mujoco_py -I/home/juan/.mujoco/mujoco200/include -I/media/juan/sdd/python/drl/code-bases/graphs/rlkit-relational/relSuite_env/lib/python3.8/site-packages/numpy/core/include -I/media/juan/sdd/python/drl/code-bases/graphs/rlkit-relational/relSuite_env/lib/python3.8/site-packages/mujoco_py/vendor/egl -I/media/juan/sdd/python/drl/code-bases/graphs/rlkit-relational/relSuite_env/include -I/usr/include/python3.8 -c /media/juan/sdd/python/drl/code-bases/graphs/rlkit-relational/relSuite_env/lib/python3.8/site-packages/mujoco_py/cymj.c -o /media/juan/sdd/python/drl/code-bases/graphs/rlkit-relational/relSuite_env/lib/python3.8/site-packages/mujoco_py/generated/_pyxbld_2.0.2.13_38_linuxgpuextensionbuilder/temp.linux-x86_64-3.8/media/juan/sdd/python/drl/code-bases/graphs/rlkit-relational/relSuite_env/lib/python3.8/site-packages/mujoco_py/cymj.o -fopenmp -w
/media/juan/sdd/python/drl/code-bases/graphs/rlkit-relational/relSuite_env/lib/python3.8/site-packages/mujoco_py/cymj.c: In function ‘__pyx_f_9mujoco_py_4cymj_11PyMjvFigure__set’:
/media/juan/sdd/python/drl/code-bases/graphs/rlkit-relational/relSuite_env/lib/python3.8/site-packages/mujoco_py/cymj.c:77676:91: error: subscripted value is neither array nor pointer nor vector
77676 | _t_1 = ((PyObject *)__pyx_f_9mujoco_py_4cymj__wrap_float_1d((&(__pyx_v_p->linewidth[0])), 0x64)); if (unlikely(!__pyx_t_1)) __PYX_ERR(4, 3829, __pyx_L1_error)
      |                                                                                    ^

/media/juan/sdd/python/drl/code-bases/graphs/rlkit-relational/relSuite_env/lib/python3.8/site-packages/mujoco_py/cymj.c: In function ‘__pyx_pf_9mujoco_py_4cymj_11PyMjvFigure_9legendoff___get__’:
/media/juan/sdd/python/drl/code-bases/graphs/rlkit-relational/relSuite_env/lib/python3.8/site-packages/mujoco_py/cymj.c:78316:55: error: ‘mjvFigure’ {aka ‘struct _mjvFigure’} has no member named ‘legendoff’; did you mean ‘legendoffset’?
78316 |   __pyx_t_1 = __Pyx_PyInt_From_int(__pyx_v_self->ptr->legendoff); if (unlikely(!__pyx_t_1)) __PYX_ERR(4, 3860, __pyx_L1_error)
      |                                                       ^~~~~~~~~
      |                                                       legendoffset
/media/juan/sdd/python/drl/code-bases/graphs/rlkit-relational/relSuite_env/lib/python3.8/site-packages/mujoco_py/cymj.c: In function ‘__pyx_pf_9mujoco_py_4cymj_11PyMjvFigure_9legendoff_2__set__’:
/media/juan/sdd/python/drl/code-bases/graphs/rlkit-relational/relSuite_env/lib/python3.8/site-packages/mujoco_py/cymj.c:78371:22: error: ‘mjvFigure’ {aka ‘struct _mjvFigure’} has no member named ‘legendoff’; did you mean ‘legendoffset’?
78371 |   __pyx_v_self->ptr->legendoff = __pyx_v_x;
      |                      ^~~~~~~~~
      |                      legendoffset
Traceback (most recent call last):
  File "/usr/lib/python3.8/distutils/unixccompiler.py", line 117, in _compile
    self.spawn(compiler_so + cc_args + [src, '-o', obj] +
  File "/usr/lib/python3.8/distutils/ccompiler.py", line 910, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/usr/lib/python3.8/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/usr/lib/python3.8/distutils/spawn.py", line 157, in _spawn_posix
    raise DistutilsExecError(
distutils.errors.DistutilsExecError: command 'x86_64-linux-gnu-gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train_binPicking.py", line 44, in <module>
    import robosuite as suite                                                           # will call all __init__ inside suite loading all relevant classes
  File "/home/juan/python/drl/toolsuites/robosuite/robosuite/robosuite/__init__.py", line 1, in <module>
    from robosuite.environments.base import make
  File "/home/juan/python/drl/toolsuites/robosuite/robosuite/robosuite/environments/__init__.py", line 1, in <module>
    from .base import REGISTERED_ENVS, MujocoEnv
  File "/home/juan/python/drl/toolsuites/robosuite/robosuite/robosuite/environments/base.py", line 2, in <module>
    from mujoco_py import MjSim, MjRenderContextOffscreen
  File "/media/juan/sdd/python/drl/code-bases/graphs/rlkit-relational/relSuite_env/lib/python3.8/site-packages/mujoco_py/__init__.py", line 3, in <module>
    from mujoco_py.builder import cymj, ignore_mujoco_warnings, functions, MujocoException
  File "/media/juan/sdd/python/drl/code-bases/graphs/rlkit-relational/relSuite_env/lib/python3.8/site-packages/mujoco_py/builder.py", line 510, in <module>
    cymj = load_cython_ext(mujoco_path)
  File "/media/juan/sdd/python/drl/code-bases/graphs/rlkit-relational/relSuite_env/lib/python3.8/site-packages/mujoco_py/builder.py", line 105, in load_cython_ext
    cext_so_path = builder.build()
  File "/media/juan/sdd/python/drl/code-bases/graphs/rlkit-relational/relSuite_env/lib/python3.8/site-packages/mujoco_py/builder.py", line 221, in build
    built_so_file_path = self._build_impl()
  File "/media/juan/sdd/python/drl/code-bases/graphs/rlkit-relational/relSuite_env/lib/python3.8/site-packages/mujoco_py/builder.py", line 291, in _build_impl
    so_file_path = super()._build_impl()
  File "/media/juan/sdd/python/drl/code-bases/graphs/rlkit-relational/relSuite_env/lib/python3.8/site-packages/mujoco_py/builder.py", line 244, in _build_impl
    dist.run_commands()
  File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/media/juan/sdd/python/drl/code-bases/graphs/rlkit-relational/relSuite_env/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/usr/lib/python3.8/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/media/juan/sdd/python/drl/code-bases/graphs/rlkit-relational/relSuite_env/lib/python3.8/site-packages/mujoco_py/builder.py", line 144, in build_extensions
    build_ext.build_extensions(self)
  File "/media/juan/sdd/python/drl/code-bases/graphs/rlkit-relational/relSuite_env/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "/usr/lib/python3.8/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/usr/lib/python3.8/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/usr/lib/python3.8/distutils/command/build_ext.py", line 528, in build_extension
    objects = self.compiler.compile(sources,
  File "/usr/lib/python3.8/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/usr/lib/python3.8/distutils/unixccompiler.py", line 120, in _compile
    raise CompileError(msg)
distutils.errors.CompileError: command 'x86_64-linux-gnu-gcc' failed with exit status 
````

**Comment by rojas70** [comment]
Actually, I had misplaced the mjkey.txt file. Instead of having it at `./mujoco` I had originally placed it at `.mujoco/mujoco2XX/bin`
