### ISSUE TITLE
 OpenGL_accelerate.errorchecker._ErrorChecker.glCheckError OpenGL.raw.EGL._errors.EGLError: <exception str() failed>

### ISSUE THREAD

**Issue by cidxb** [deepmind/mujoco#765]
Hi, friends.
System: Ubuntu 22.04
SSH server

I have run into a problem with OpenGL.
So at first, I have the 

```
  File "/home/jeffery/anaconda3/envs/RL-server/lib/python3.10/site-packages/glfw/__init__.py", line 657, in callback_wrapper
    @functools.wraps(func)
KeyboardInterrupt: 
/home/jeffery/anaconda3/envs/RL-server/lib/python3.10/site-packages/glfw/__init__.py:912: GLFWError: (65537) b'The GLFW library is not initialized'
  warnings.warn(message, GLFWError)
Traceback (most recent call last):
  File "/home/jeffery/Workspace/rl_Pick_Place/mujoco_test.py", line 2294, in <module>
    controller = PickPlace_Mujoco_env(gripper_xml,sim_render = False,dt=0.002,record=False)
  File "/home/jeffery/Workspace/rl_Pick_Place/PickPlace_Mujoco_env.py", line 82, in __init__
    super().__init__(modelpath,act_opt,frame_skip,dof,image_width,image_height,show_obs,dt,record,sim_render)####继承父类初始化属性
  File "/home/jeffery/Workspace/rl_Pick_Place/PickPlace_env.py", line 141, in __init__
    obs=self.reset()
  File "/home/jeffery/Workspace/rl_Pick_Place/PickPlace_Mujoco_env.py", line 1200, in reset
    return self.get_observation(show=False)
  File "/home/jeffery/Workspace/rl_Pick_Place/PickPlace_env.py", line 408, in get_observation
    rgb, depth = self.get_image_data(show=show)
  File "/home/jeffery/Workspace/rl_Pick_Place/PickPlace_Mujoco_env.py", line 897, in get_image_data
    renderer_rgb=mj.Renderer(self.model,width=self.IMAGE_WIDTH,height=self.IMAGE_HEIGHT)
  File "/home/jeffery/anaconda3/envs/RL-server/lib/python3.10/site-packages/mujoco/renderer.py", line 86, in __init__
    self._mjr_context = _render.MjrContext(
mujoco.FatalError: gladLoadGL error
```

Then I have used the  command 
export MUJOCO_GL=egl

It solves the problem, and the script works.

But the error became 
```
exception ignored in: <function GLContext.__del__ at 0x7f46c576f250>
Traceback (most recent call last):
  File "/home/jeffery/anaconda3/envs/RL-server/lib/python3.10/site-packages/mujoco/egl/__init__.py", line 130, in __del__
  File "/home/jeffery/anaconda3/envs/RL-server/lib/python3.10/site-packages/mujoco/egl/__init__.py", line 123, in free
  File "/home/jeffery/anaconda3/envs/RL-server/lib/python3.10/site-packages/OpenGL/error.py", line 230, in glCheckError
OpenGL.raw.EGL._errors.EGLError: <exception str() failed>
```

and while I  install PyOpenGL-accelerate, it change to (guess is the same)
```
Exception ignored in: <function GLContext.__del__ at 0x7f1c14000dc0>
Traceback (most recent call last):
  File "/home/jeffery/anaconda3/envs/RL-server/lib/python3.10/site-packages/mujoco/egl/__init__.py", line 130, in __del__
  File "/home/jeffery/anaconda3/envs/RL-server/lib/python3.10/site-packages/mujoco/egl/__init__.py", line 123, in free
  File "src/errorchecker.pyx", line 58, in OpenGL_accelerate.errorchecker._ErrorChecker.glCheckError
OpenGL.raw.EGL._errors.EGLError: <exception str() failed>
```
wanna know if anybody has the solution for this problem.
Thx you !!

ps: I have checked for a lot of posts, so I have installed that libxxx library stuff and set the DISPLAY=":0.0"
or https://github.com/deepmind/mujoco/issues/572
https://github.com/deepmind/dm_control#rendering
https://github.com/openai/gym/issues/879

Is it becasue the SSH server don't have display monitor ? But I thought that is the EGL for ?"Headless + hardware accelerate"

**Comment by cidxb** [comment]
I  gonna close this topic , since I found https://github.com/deepmind/mujoco/issues/700 .

**Comment by cidxb** [comment]
For fellows who will encounter glfw problem
here is a solution :
  - https://stackoverflow.com/questions/71010343/cannot-load-swrast-and-iris-drivers-in-fedora-35
  - export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libstdc++.so.6
basically is the do a soft connection to your dll

**Comment by saran-t** [comment]
@cidxb I'd be extremely cautious about doing that. Sideloading different versions of `libstdc++` is fairly likely to result in random, subtle errors affecting anything that's loaded into the process.

**Comment by ctbfl** [comment]
Maybe because you do not use `env.close()` to close the env?
