### ISSUE TITLE
Gymnasium support for Mac Arm64 CPUs

### ISSUE THREAD

**Issue by achouliaras** [deepmind/mujoco#907]
Hi,

I'm a student and I'm trying to use MuJoCo via Gymnasium environments.

I'm looking for some help with the setup for MacOS with the Arm Cpu (M2).

I used the commands: 
`pip install mujoco`
`pip install gymnasium[mujoco]`

but I get the following error when I try to import a MuJoCo-related environment:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/lib/python3.11/site-packages/gymnasium/envs/registration.py", line 755, in make
    env_creator = load_env_creator(env_spec.entry_point)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/gymnasium/envs/registration.py", line 553, in load_env_creator
    mod = importlib.import_module(mod_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1128, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/homebrew/lib/python3.11/site-packages/gymnasium/envs/mujoco/__init__.py", line 1, in <module>
    from gymnasium.envs.mujoco.mujoco_env import MujocoEnv, MuJocoPyEnv  # isort:skip
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/gymnasium/envs/mujoco/mujoco_env.py", line 12, in <module>
    import mujoco_py
  File "/opt/homebrew/lib/python3.11/site-packages/mujoco_py/__init__.py", line 2, in <module>
    from mujoco_py.builder import cymj, ignore_mujoco_warnings, functions, MujocoException
  File "/opt/homebrew/lib/python3.11/site-packages/mujoco_py/builder.py", line 504, in <module>
    cymj = load_cython_ext(mujoco_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/mujoco_py/builder.py", line 110, in load_cython_ext
    cext_so_path = builder.build()
                   ^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/mujoco_py/builder.py", line 226, in build
    built_so_file_path = self._build_impl()
                         ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/mujoco_py/builder.py", line 333, in _build_impl
    raise RuntimeError(
RuntimeError: Could not find supported GCC executable.

HINT: On OS X, install GCC 9.x with `brew install gcc@9`. or `port install gcc9`.

I tried installing GCC 9 but it isn't available for OSX Arm64 architectures.

Also, I downloaded the dmg version but I don't know how to link it with Gymnasium. 

How do I install the MuJoCo Engine so that it can be linked to Gymnasium environments?
Has anyone managed to do it for Mac Arm64 architecture?

**Comment by saran-t** [comment]
You're better off bringing this issue up with the [Gymnasium maintainers](https://github.com/Farama-Foundation/Gymnasium). For some reasons you're still hitting `mujoco_py` which is a deprecated, unmaintained, third-party Python bindings that no longer supports newer versions of MuJoCo.
